name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']
    
    staging:
      +schema: staging
    
    intermediate:
      +schema: intermediate

    marts:
      core:
        +schema: core_reporting
      finance:
        +schema: finance
      product:
        +schema: product
  
  # hiding a dbt package: the models folder for this package will not be displayed in the documentation and DAG.
  # yet this only hide the models folder. References to the package (macros, seeds) still displayed in docs
  # https://github.com/dbt-labs/dbt-core/issues/8061
  dbt_project_evaluator:
    +docs:
      show: false


seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

# set your model fanout threshold to 10 instead of 3: to avoid is_empty_fct_model_fanout_ warning
vars:
  dbt_project_evaluator:
    models_fanout_threshold: 10

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"